spring:
  profiles:
    active: dev
  application:
    name: jww-ump-dubbo-consumer
dubbo:
  application:
    name: jww-ump-dubbo-consumer
    owner: jww-ump-dubbo-consumer

auto:
  swagger2:
    apiInfo:
      version: 1.0.0
      title: 运营管理平台
      description: 运营管理平台接口文档