spring:
  redis:
    database: 0
    host: 47.99.90.68
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 200
      max-wait: 10000
      max-idle: 150
      min-idle: 50
    lock:
      waitTimeOut: 5
      lockTimeOut: 10
  session:
    timeout: 60
  activemq:
    broker-url: tcp://47.99.90.68:61616
    user: admin
    password: admin
    pool:
      enabled: false #如果此处设置为true，需要加如下的依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
      #<dependency>
      #         <groupId>org.apache.activemq</groupId>
      #            <artifactId>activemq-pool</artifactId>
      #        <!-- <version>5.7.0</version> -->
      #    </dependency>
  zipkin:
    baseUrl:  http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
server:
  port: 8081

dubbo:
  registry:
    protocol: zookeeper
    address: 47.99.90.68:2181
  trace:
    enabled: true
  reference:
    group: test

logging:
  level:
     root: info
jwt:
  isOpen: 1             # 是否开户jwt校验，1：开启；0：关闭
  header: Authorization   #http请求头所需要的字段
  secret: Secret        #jwt秘钥
  expiration: 300       #5分钟 单位:秒
  auth-path: wx/login     #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  excludePaths: (/swagger.*)|(/api-docs.*)|(/callback.*)|(/configuration/.*)|(/*/configuration/.*)|(/webjars/.*)|(/v2/.*)  #不校验路径