spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 150
        min-idle: 50
      timeout: 10000
    lock:
      waitTimeOut: 5
      lockTimeOut: 10
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 50Mb
      max-request-size: 100Mb
  activemq:
    broker-url: tcp://47.99.90.68:61616
    user: admin
    password: admin
    pool:
      enabled: false #如果此处设置为true，需要加如下的依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
      #<dependency>
      #         <groupId>org.apache.activemq</groupId>
      #            <artifactId>activemq-pool</artifactId>
      #        <!-- <version>5.7.0</version> -->
      #    </dependency>
  zipkin:
    baseUrl:  http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
  dubbo:
    registry:
      protocol: zookeeper
      address: 47.99.90.68:2181
    trace:
      enabled: true
    reference:
      group: test
idworker:
  worker-id: 10
server:
  port: 8089
  servlet:
    session:
      timeout: PT60M
oss:
  type: 2
  accessKeyId: AKIDlQNOI539ORL3axmII6i8MO9tUt9GluWw
  accessKeySecret: NZgbKrCoIaihV7XlnttiLm2B7wayEIBt
  bucketName: aihuishou-1251883742
  domain: https://aihuishou-1251883742.cos.ap-shanghai.myqcloud.com
  endPoint: ap-shanghai

logging:
  level:
    root: info