spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 150
        min-idle: 50
      timeout: 10000
    lock:
      waitTimeOut: 5
      lockTimeOut: 10
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 50Mb
      max-request-size: 100Mb
  activemq:
    broker-url: tcp://47.99.90.68:61616
    user: admin
    password: admin
    pool:
      enabled: false #如果此处设置为true，需要加如下的依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
      #<dependency>
      #         <groupId>org.apache.activemq</groupId>
      #            <artifactId>activemq-pool</artifactId>
      #        <!-- <version>5.7.0</version> -->
      #    </dependency>
  application:
    name: jww-ump-dubbo-consumer
  zipkin:
    baseUrl:  http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
  dubbo:
    application:
      name: jww-ump-dubbo-consumer
      owner: jww-ump-dubbo-consumer
    registry:
      protocol: zookeeper
      address: 192.168.0.74:2181,192.168.0.74:2182,192.168.0.74:2183
    trace:
      enabled: true
    reference:
      group: prod
idworker:
  worker-id: 10
server:
  port: 8089
  servlet:
    session:
      timeout: PT60M

logging:
  level:
    root: info